export const COMPANY = {
  name: "ZJ Infosystem",
  tagline: "Transforming Technology. Empowering Businesses.",
  founded: "2021",
  founder: "Mr. Dadasaheb Shaikh",
  email: "zahid.shaikh@zjinfosystem.com",
  phone: "+91 73873 08578",
  whatsapp: "+91 73873 08578",
  address: {
    lines: [
      "The Eyerish, villa -13, SR No. 56/9, Gulmohar Park, Satav Nagar, Hadapsar, Pune, 411028",
      "Maharashtra, India",
    ],
  },
  social: {
    linkedin: "https://www.linkedin.com/company/zj-infosystems-india-private-limited",
  },
};

export const SERVICES = [
  { slug: "it-infrastructure", title: "IT Infrastructure Development", short: "Architect and deploy resilient, future-ready IT foundations.", icon: "Server",
    overview: "We design, build and operate enterprise-grade IT infrastructures engineered for scale, uptime and predictable performance.",
    benefits: ["99.99% uptime targets", "Reduced total cost of ownership", "Elastic capacity planning", "Vendor-neutral design"],
    features: ["Compute & storage design", "Virtualization (VMware / Hyper-V)", "Backup & disaster recovery", "Monitoring & observability"],
    industries: ["Enterprise", "Government", "Healthcare", "Finance"] },
  { slug: "software-development", title: "Software Development", short: "Custom applications engineered around your workflow.", icon: "Code2",
    overview: "From product MVPs to mission-critical line-of-business systems — we ship secure, maintainable software with a delivery discipline.",
    benefits: ["Faster time to market", "Ownership of source & IP", "Modern, testable architecture", "Long-term maintainability"],
    features: ["Web, mobile & API platforms", "Cloud-native micro-services", "DevOps & CI/CD pipelines", "QA automation"],
    industries: ["Finance", "Healthcare", "Retail", "Education"] },
  { slug: "it-auditing", title: "IT Auditing", short: "Independent assessment of risk, controls and compliance.", icon: "ClipboardCheck",
    overview: "Comprehensive audits that surface exposure, benchmark controls against ISO/NIST standards and produce board-ready reporting.",
    benefits: ["Reduced regulatory risk", "Board-ready evidence", "Actionable roadmap", "Improved cyber posture"],
    features: ["Controls testing", "Gap analysis vs. ISO 27001 / NIST", "Vendor risk reviews", "Remediation planning"],
    industries: ["Finance", "Government", "Healthcare"] },
  { slug: "microsoft-infrastructure", title: "Microsoft Infrastructure Services", short: "Azure, Windows Server, Active Directory and Microsoft 365 — engineered right.", icon: "Cloud",
    overview: "Certified Microsoft engineers implement, migrate and modernize the full Microsoft stack from identity to workload.",
    benefits: ["Seamless Azure adoption", "Modern identity & Zero Trust", "Reduced licensing spend", "Optimized productivity"],
    features: ["Azure landing zones", "Active Directory & Entra ID", "Microsoft 365 rollouts", "Windows Server modernization"],
    industries: ["Enterprise", "SME", "Education", "Government"] },
  { slug: "network-design", title: "Network Design & Wireless Solutions", short: "Enterprise networks tuned for performance, security and scale.", icon: "Wifi",
    overview: "We design LAN, WAN, SD-WAN and high-density wireless networks that meet the demands of modern digital workplaces.",
    benefits: ["Predictable performance", "High-density Wi-Fi coverage", "Segmented, secure fabric", "Simplified operations"],
    features: ["Cisco / Aruba deployments", "SD-WAN & MPLS", "Wi-Fi 6 / 6E design", "Network access control"],
    industries: ["Manufacturing", "Retail", "Hospitality", "Education"] },
  { slug: "security-networking", title: "Security & Networking", short: "Defend the perimeter, the endpoint and everything in between.", icon: "ShieldCheck",
    overview: "A layered security practice covering perimeter, endpoint, identity and data — with 24×7 monitoring options.",
    benefits: ["Reduced attack surface", "Faster incident response", "Compliance alignment", "Executive-level visibility"],
    features: ["Firewalls & UTM", "Endpoint protection (EDR/XDR)", "Zero Trust access", "SOC & SIEM"],
    industries: ["Finance", "Healthcare", "Government"] },
  { slug: "building-management", title: "Building Management Services", short: "Intelligent building systems that lower cost and lift comfort.", icon: "Building2",
    overview: "IoT-driven BMS integration across HVAC, access, CCTV and energy — unified in a single pane of glass.",
    benefits: ["Lower energy spend", "Centralized monitoring", "Predictive maintenance", "Improved tenant experience"],
    features: ["HVAC / BMS integration", "IP-CCTV & access control", "Energy analytics", "Digital twin dashboards"],
    industries: ["Real Estate", "Hospitality", "Manufacturing"] },
  { slug: "data-centre", title: "Data Centre Management", short: "Turn-key data centre design, build and operation.", icon: "DatabaseZap",
    overview: "End-to-end data centre lifecycle — from Tier-III design to daily NOC operations — engineered for continuity.",
    benefits: ["Tier-III readiness", "24×7 NOC support", "Optimized PUE", "Migration confidence"],
    features: ["Rack, power & cooling design", "Colocation strategy", "Physical security", "Runbook automation"],
    industries: ["Enterprise", "BFSI", "Government"] },
  { slug: "managed-it", title: "Managed IT Services", short: "One accountable partner for every layer of your stack.", icon: "Headphones",
    overview: "Fixed-fee managed services covering helpdesk, endpoint, servers, network and cloud — with SLA-backed response.",
    benefits: ["Predictable IT spend", "SLA-backed response", "Proactive maintenance", "Focus on core business"],
    features: ["24×7 service desk", "Patch & vulnerability mgmt.", "Asset & license mgmt.", "Executive reporting"],
    industries: ["SME", "Enterprise", "Education"] },
  { slug: "hr-consultancy", title: "HR Consultancy", short: "Human-capital strategy aligned to technology outcomes.", icon: "Users",
    overview: "We help IT-heavy organizations attract, develop and retain the talent that keeps transformation moving.",
    benefits: ["Reduced attrition", "Faster hiring cycles", "Aligned compensation", "Compliance-ready policies"],
    features: ["Talent acquisition", "Policy & compliance", "Performance frameworks", "Learning & development"],
    industries: ["Enterprise", "SME", "Startups"] },
  { slug: "accounting-auditing", title: "Accounting & Auditing", short: "Financial clarity, audit-ready records, always.", icon: "FileSpreadsheet",
    overview: "Outsourced accounting and statutory audit support with modern tooling and full audit trails.",
    benefits: ["Real-time financial visibility", "Audit-ready books", "Reduced back-office cost", "Regulatory confidence"],
    features: ["Bookkeeping & MIS", "Statutory audit support", "GST & tax filings", "Internal controls"],
    industries: ["SME", "Enterprise", "Non-profit"] },
  { slug: "financial-consultancy", title: "Financial Consultancy", short: "Strategy, forecasting and CFO-level guidance on demand.", icon: "LineChart",
    overview: "Fractional CFO services and financial strategy for organizations navigating growth, funding or transformation.",
    benefits: ["Board-ready reporting", "Cash-flow discipline", "Scenario planning", "Fundraising support"],
    features: ["Financial modelling", "Budget & forecast", "Investor reporting", "Cost optimization"],
    industries: ["Startups", "SME", "Enterprise"] },
  { slug: "data-processing", title: "Data Processing & Management", short: "Turn raw data into governed, decision-ready insight.", icon: "Database",
    overview: "Data engineering, warehousing and governance services that make your organization measurably data-driven.",
    benefits: ["Single source of truth", "Governed data access", "Faster analytics", "AI-ready foundations"],
    features: ["ETL / ELT pipelines", "Cloud data warehouses", "Data governance", "BI enablement"],
    industries: ["Finance", "Healthcare", "Retail", "Manufacturing"] },
];

export const INDUSTRIES = [
  { title: "Education", icon: "GraduationCap", desc: "Smart classrooms, secure campus networks and cloud-first academic platforms that scale with enrollment." },
  { title: "Healthcare", icon: "HeartPulse", desc: "HIPAA-conscious infrastructure, secure EMR hosting and connected medical device networks." },
  { title: "Manufacturing", icon: "Factory", desc: "OT/IT convergence, industrial IoT and shop-floor connectivity engineered for uptime." },
  { title: "Finance", icon: "Landmark", desc: "Hardened networks, layered security and compliance-first cloud for BFSI institutions." },
  { title: "Government", icon: "Building", desc: "Sovereign-ready infrastructure, citizen service platforms and secure inter-department networks." },
  { title: "Retail", icon: "ShoppingBag", desc: "Omni-channel commerce, PoS networks and analytics that turn footfall into revenue." },
  { title: "Hospitality", icon: "Hotel", desc: "Guest-grade Wi-Fi, PMS integration and building automation for premium experiences." },
  { title: "Professional Services", icon: "Briefcase", desc: "Secure remote work, document management and client portals for consulting firms." },
];

export const WHY_US = [
  { title: "Enterprise Expertise", desc: "A team seasoned across BFSI, government and large-enterprise engagements.", icon: "Award" },
  { title: "Reliable Support", desc: "SLA-backed, 24×7 response with senior engineers on every escalation.", icon: "LifeBuoy" },
  { title: "Secure Infrastructure", desc: "Security-first architecture aligned to ISO 27001 and NIST frameworks.", icon: "ShieldCheck" },
  { title: "Modern Technologies", desc: "Microsoft, VMware, Cisco, Linux, Docker and cloud-native tooling.", icon: "Cpu" },
  { title: "Scalable Solutions", desc: "Designs that grow with your business — from 50 seats to 50,000.", icon: "TrendingUp" },
  { title: "Customer Focus", desc: "Named account teams and quarterly business reviews for every client.", icon: "Users" },
  { title: "Long-Term Partnership", desc: "Multi-year engagements built on transparency and outcomes.", icon: "Handshake" },
  { title: "Fast Deployment", desc: "Proven delivery playbooks that shorten time-to-value.", icon: "Rocket" },
  { title: "Industry Best Practices", desc: "ITIL, DevOps and Zero Trust practices baked into every engagement.", icon: "BookCheck" },
];

export const STATS = [
  { value: 250, suffix: "+", label: "Enterprise Projects Delivered" },
  { value: 99.99, suffix: "%", label: "Infrastructure Uptime SLA", decimals: 2 },
  { value: 24, suffix: "×7", label: "Managed Support Coverage" },
  { value: 15, suffix: "+", label: "Industries Served" },
];

export const TECHNOLOGIES = [
  { name: "Microsoft", key: "SiMicrosoft" },
  { name: "Microsoft Azure", key: "SiMicrosoftazure" },
  { name: "Windows Server", key: "SiWindows" },
  { name: "Microsoft 365", key: "SiMicrosoftoffice" },
  { name: "VMware", key: "SiVmware" },
  { name: "Cisco", key: "SiCisco" },
  { name: "Linux", key: "SiLinux" },
  { name: "Docker", key: "SiDocker" },
  { name: "Kubernetes", key: "SiKubernetes" },
  { name: "AWS", key: "SiAmazonwebservices" },
  { name: "Google Cloud", key: "SiGooglecloud" },
  { name: "Oracle", key: "SiOracle" },
  { name: "Cloudflare", key: "SiCloudflare" },
  { name: "Fortinet", key: "SiFortinet" },
  { name: "Ubuntu", key: "SiUbuntu" },
  { name: "Red Hat", key: "SiRedhat" },
];

export const TIMELINE = [
  { year: "2021", title: "ZJ Infosystem Founded", desc: "Established in Pune under the leadership of Mr. Dadasaheb Shaikh with a mission to bring enterprise-grade IT to Indian businesses." },
  { year: "2022", title: "Enterprise Practice Formed", desc: "Built dedicated practices across Microsoft, networking and cybersecurity — earning our first Fortune-list engagements." },
  { year: "2023", title: "Managed Services Launched", desc: "Rolled out 24×7 managed IT services with SLA-backed response for BFSI and healthcare clients." },
  { year: "2024", title: "Cloud & Security Expansion", desc: "Deepened Azure, Zero Trust and data-centre modernization capabilities across a growing customer base." },
  { year: "2025", title: "National Footprint", desc: "Serving customers across India with an expanded delivery team and multi-city partner presence." },
];
